name: ecuaciones_diferenciales
description: "App para resolver ecuaciones diferenciales."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_math_fork: ^0.7.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
    # - assets/images/icono.png

flutter_icons:
  image_path: 'assets/images/icono.png'
  android: true